//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reservationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservationTable
    {
        public int Id { get; set; }
        public string location { get; set; }
        public string chkInDate { get; set; }
        public string chkOutdate { get; set; }
        public string roomQty { get; set; }
    }
}
